//
// Created by Paul Bittner on 20.03.2021.
//

#include "polypropylene/stdutils/StringUtils.h"
#include "paxcore/io/Keys.h"

#define PAX_ADDMAPPINGFOR(k) \
    ktos[Key::k] = #k;     \
    stok[#k] = Key::k;

std::ostream & operator<<(std::ostream & str, const PAX::Key & k) {
    return str << PAX::TryParser<std::string, PAX::Key>::GetKeyToStringMap().at(k);
}

namespace PAX {
    Key TryParser<std::string, Key>::tryParse(const std::string & inputKey) {
        const std::string s = String::UpperCase(inputKey);
        const auto & keyMap = GetStringToKeyMap();
        const auto & it = keyMap.find(s);
        if (it != keyMap.end()) {
            return it->second;
        }
        PAX_THROW_RUNTIME_ERROR("Given key \"" << inputKey << "\" could not be parsed!");
    }

    std::map<std::string, Key> & TryParser<std::string, Key>::GetUninitializedStringToKeyMap() {
        static std::map<std::string, Key> strToK;
        return strToK;
    }

    std::map<Key, std::string> & TryParser<std::string, Key>::GetUninitializedKeyToStringMap() {
        static std::map<Key, std::string> kToStr;
        return kToStr;
    }

    std::map<std::string, Key> & TryParser<std::string, Key>::GetMutableStringToKeyMap() {
        auto & strToK = GetUninitializedStringToKeyMap();
        if (strToK.empty()) {
            InitMaps();
        }
        return strToK;
    }

    std::map<Key, std::string> & TryParser<std::string, Key>::GetMutableKeyToStringMap() {
        auto & kToStr = GetUninitializedKeyToStringMap();
        if (kToStr.empty()) {
            InitMaps();
        }
        return kToStr;
    }

    const std::map<std::string, Key> & TryParser<std::string, Key>::GetStringToKeyMap() {
        return GetMutableStringToKeyMap();
    }

    const std::map<Key, std::string> & TryParser<std::string, Key>::GetKeyToStringMap() {
        return GetMutableKeyToStringMap();
    }
    
    void TryParser<std::string, Key>::InitMaps() {
        auto & stok = GetUninitializedStringToKeyMap();
        auto & ktos = GetUninitializedKeyToStringMap();

        PAX_ADDMAPPINGFOR(NONE)
        PAX_ADDMAPPINGFOR(A)
        PAX_ADDMAPPINGFOR(B)
        PAX_ADDMAPPINGFOR(C)
        PAX_ADDMAPPINGFOR(D)
        PAX_ADDMAPPINGFOR(E)
        PAX_ADDMAPPINGFOR(F)
        PAX_ADDMAPPINGFOR(G)
        PAX_ADDMAPPINGFOR(H)
        PAX_ADDMAPPINGFOR(I)
        PAX_ADDMAPPINGFOR(J)
        PAX_ADDMAPPINGFOR(K)
        PAX_ADDMAPPINGFOR(L)
        PAX_ADDMAPPINGFOR(M)
        PAX_ADDMAPPINGFOR(N)
        PAX_ADDMAPPINGFOR(O)
        PAX_ADDMAPPINGFOR(P)
        PAX_ADDMAPPINGFOR(Q)
        PAX_ADDMAPPINGFOR(R)
        PAX_ADDMAPPINGFOR(S)
        PAX_ADDMAPPINGFOR(T)
        PAX_ADDMAPPINGFOR(U)
        PAX_ADDMAPPINGFOR(V)
        PAX_ADDMAPPINGFOR(W)
        PAX_ADDMAPPINGFOR(X)
        PAX_ADDMAPPINGFOR(Y)
        PAX_ADDMAPPINGFOR(Z)

        PAX_ADDMAPPINGFOR(K1)
        PAX_ADDMAPPINGFOR(K2)
        PAX_ADDMAPPINGFOR(K3)
        PAX_ADDMAPPINGFOR(K4)
        PAX_ADDMAPPINGFOR(K5)
        PAX_ADDMAPPINGFOR(K6)
        PAX_ADDMAPPINGFOR(K7)
        PAX_ADDMAPPINGFOR(K8)
        PAX_ADDMAPPINGFOR(K9)
        PAX_ADDMAPPINGFOR(K0)

        PAX_ADDMAPPINGFOR(RETURN)
        PAX_ADDMAPPINGFOR(ESCAPE)
        PAX_ADDMAPPINGFOR(BACKSPACE)
        PAX_ADDMAPPINGFOR(TAB)
        PAX_ADDMAPPINGFOR(SPACE)

        PAX_ADDMAPPINGFOR(MINUS)
        PAX_ADDMAPPINGFOR(EQUALS)
        PAX_ADDMAPPINGFOR(LEFTBRACKET)
        PAX_ADDMAPPINGFOR(RIGHTBRACKET)
        PAX_ADDMAPPINGFOR(BACKSLASH)
        PAX_ADDMAPPINGFOR(NONUSHASH)
        PAX_ADDMAPPINGFOR(SEMICOLON)
        PAX_ADDMAPPINGFOR(APOSTROPHE)
        PAX_ADDMAPPINGFOR(GRAVE)
        PAX_ADDMAPPINGFOR(COMMA)
        PAX_ADDMAPPINGFOR(PERIOD)
        PAX_ADDMAPPINGFOR(SLASH)

        PAX_ADDMAPPINGFOR(CAPSLOCK)

        PAX_ADDMAPPINGFOR(F1)
        PAX_ADDMAPPINGFOR(F2)
        PAX_ADDMAPPINGFOR(F3)
        PAX_ADDMAPPINGFOR(F4)
        PAX_ADDMAPPINGFOR(F5)
        PAX_ADDMAPPINGFOR(F6)
        PAX_ADDMAPPINGFOR(F7)
        PAX_ADDMAPPINGFOR(F8)
        PAX_ADDMAPPINGFOR(F9)
        PAX_ADDMAPPINGFOR(F10)
        PAX_ADDMAPPINGFOR(F11)
        PAX_ADDMAPPINGFOR(F12)

        PAX_ADDMAPPINGFOR(PRINTSCREEN)
        PAX_ADDMAPPINGFOR(SCROLLLOCK)
        PAX_ADDMAPPINGFOR(PAUSE)
        PAX_ADDMAPPINGFOR(INSERT)
        PAX_ADDMAPPINGFOR(HOME)
        PAX_ADDMAPPINGFOR(PAGEUP)

        PAX_ADDMAPPINGFOR(END)
        PAX_ADDMAPPINGFOR(PAGEDOWN)
        PAX_ADDMAPPINGFOR(RIGHT)
        PAX_ADDMAPPINGFOR(LEFT)
        PAX_ADDMAPPINGFOR(DOWN)
        PAX_ADDMAPPINGFOR(UP)

        PAX_ADDMAPPINGFOR(NUMLOCKCLEAR)

        PAX_ADDMAPPINGFOR(KP_DIVIDE)
        PAX_ADDMAPPINGFOR(KP_MULTIPLY)
        PAX_ADDMAPPINGFOR(KP_MINUS)
        PAX_ADDMAPPINGFOR(KP_PLUS)
        PAX_ADDMAPPINGFOR(KP_ENTER)
        PAX_ADDMAPPINGFOR(KP_1)
        PAX_ADDMAPPINGFOR(KP_2)
        PAX_ADDMAPPINGFOR(KP_3)
        PAX_ADDMAPPINGFOR(KP_4)
        PAX_ADDMAPPINGFOR(KP_5)
        PAX_ADDMAPPINGFOR(KP_6)
        PAX_ADDMAPPINGFOR(KP_7)
        PAX_ADDMAPPINGFOR(KP_8)
        PAX_ADDMAPPINGFOR(KP_9)
        PAX_ADDMAPPINGFOR(KP_0)
        PAX_ADDMAPPINGFOR(KP_PERIOD)

        PAX_ADDMAPPINGFOR(NONUSBACKSLASH)
        PAX_ADDMAPPINGFOR(APPLICATION)
        PAX_ADDMAPPINGFOR(POWER)
        PAX_ADDMAPPINGFOR(KP_EQUALS)
        PAX_ADDMAPPINGFOR(F13)
        PAX_ADDMAPPINGFOR(F14)
        PAX_ADDMAPPINGFOR(F15)
        PAX_ADDMAPPINGFOR(F16)
        PAX_ADDMAPPINGFOR(F17)
        PAX_ADDMAPPINGFOR(F18)
        PAX_ADDMAPPINGFOR(F19)
        PAX_ADDMAPPINGFOR(F20)
        PAX_ADDMAPPINGFOR(F21)
        PAX_ADDMAPPINGFOR(F22)
        PAX_ADDMAPPINGFOR(F23)
        PAX_ADDMAPPINGFOR(F24)
        PAX_ADDMAPPINGFOR(EXECUTE)
        PAX_ADDMAPPINGFOR(HELP)
        PAX_ADDMAPPINGFOR(MENU)
        PAX_ADDMAPPINGFOR(SELECT)
        PAX_ADDMAPPINGFOR(STOP)
        PAX_ADDMAPPINGFOR(AGAIN)
        PAX_ADDMAPPINGFOR(UNDO)
        PAX_ADDMAPPINGFOR(CUT)
        PAX_ADDMAPPINGFOR(COPY)
        PAX_ADDMAPPINGFOR(PASTE)
        PAX_ADDMAPPINGFOR(FIND)
        PAX_ADDMAPPINGFOR(MUTE)
        PAX_ADDMAPPINGFOR(VOLUMEUP)
        PAX_ADDMAPPINGFOR(VOLUMEDOWN)

        PAX_ADDMAPPINGFOR(KP_COMMA)
        PAX_ADDMAPPINGFOR(KP_EQUALSAS400)

        PAX_ADDMAPPINGFOR(INTERNATIONAL1)
        PAX_ADDMAPPINGFOR(INTERNATIONAL2)
        PAX_ADDMAPPINGFOR(INTERNATIONAL3)
        PAX_ADDMAPPINGFOR(INTERNATIONAL4)
        PAX_ADDMAPPINGFOR(INTERNATIONAL5)
        PAX_ADDMAPPINGFOR(INTERNATIONAL6)
        PAX_ADDMAPPINGFOR(INTERNATIONAL7)
        PAX_ADDMAPPINGFOR(INTERNATIONAL8)
        PAX_ADDMAPPINGFOR(INTERNATIONAL9)
        PAX_ADDMAPPINGFOR(LANG1)
        PAX_ADDMAPPINGFOR(LANG2)
        PAX_ADDMAPPINGFOR(LANG3)
        PAX_ADDMAPPINGFOR(LANG4)
        PAX_ADDMAPPINGFOR(LANG5)
        PAX_ADDMAPPINGFOR(LANG6)
        PAX_ADDMAPPINGFOR(LANG7)
        PAX_ADDMAPPINGFOR(LANG8)
        PAX_ADDMAPPINGFOR(LANG9)

        PAX_ADDMAPPINGFOR(ALTERASE)
        PAX_ADDMAPPINGFOR(SYSREQ)
        PAX_ADDMAPPINGFOR(CANCEL)
        PAX_ADDMAPPINGFOR(CLEAR)
        PAX_ADDMAPPINGFOR(PRIOR)
        PAX_ADDMAPPINGFOR(RETURN2)
        PAX_ADDMAPPINGFOR(SEPARATOR)

        PAX_ADDMAPPINGFOR(OPER)
        PAX_ADDMAPPINGFOR(CLEARAGAIN)
        PAX_ADDMAPPINGFOR(CRSEL)
        PAX_ADDMAPPINGFOR(EXSEL)

        PAX_ADDMAPPINGFOR(KP_00)
        PAX_ADDMAPPINGFOR(KP_000)
        PAX_ADDMAPPINGFOR(THOUSANDSSEPARATOR)
        PAX_ADDMAPPINGFOR(DECIMALSEPARATOR)
        PAX_ADDMAPPINGFOR(CURRENCYUNIT)
        PAX_ADDMAPPINGFOR(CURRENCYSUBUNIT)
        PAX_ADDMAPPINGFOR(KP_LEFTPAREN)
        PAX_ADDMAPPINGFOR(KP_RIGHTPAREN)
        PAX_ADDMAPPINGFOR(KP_LEFTBRACE)
        PAX_ADDMAPPINGFOR(KP_RIGHTBRACE)
        PAX_ADDMAPPINGFOR(KP_TAB)
        PAX_ADDMAPPINGFOR(KP_BACKSPACE)
        PAX_ADDMAPPINGFOR(KP_A)
        PAX_ADDMAPPINGFOR(KP_B)
        PAX_ADDMAPPINGFOR(KP_C)
        PAX_ADDMAPPINGFOR(KP_D)
        PAX_ADDMAPPINGFOR(KP_E)
        PAX_ADDMAPPINGFOR(KP_F)
        PAX_ADDMAPPINGFOR(KP_XOR)
        PAX_ADDMAPPINGFOR(KP_POWER)
        PAX_ADDMAPPINGFOR(KP_PERCENT)
        PAX_ADDMAPPINGFOR(KP_LESS)
        PAX_ADDMAPPINGFOR(KP_GREATER)
        PAX_ADDMAPPINGFOR(KP_AMPERSAND)
        PAX_ADDMAPPINGFOR(KP_DBLAMPERSAND)
        PAX_ADDMAPPINGFOR(KP_VERTICALBAR)
        PAX_ADDMAPPINGFOR(KP_DBLVERTICALBAR)
        PAX_ADDMAPPINGFOR(KP_COLON)
        PAX_ADDMAPPINGFOR(KP_HASH)
        PAX_ADDMAPPINGFOR(KP_SPACE)
        PAX_ADDMAPPINGFOR(KP_AT)
        PAX_ADDMAPPINGFOR(KP_EXCLAM)
        PAX_ADDMAPPINGFOR(KP_MEMSTORE)
        PAX_ADDMAPPINGFOR(KP_MEMRECALL)
        PAX_ADDMAPPINGFOR(KP_MEMCLEAR)
        PAX_ADDMAPPINGFOR(KP_MEMADD)
        PAX_ADDMAPPINGFOR(KP_MEMSUBTRACT)
        PAX_ADDMAPPINGFOR(KP_MEMMULTIPLY)
        PAX_ADDMAPPINGFOR(KP_MEMDIVIDE)
        PAX_ADDMAPPINGFOR(KP_PLUSMINUS)
        PAX_ADDMAPPINGFOR(KP_CLEAR)
        PAX_ADDMAPPINGFOR(KP_CLEARENTRY)
        PAX_ADDMAPPINGFOR(KP_BINARY)
        PAX_ADDMAPPINGFOR(KP_OCTAL)
        PAX_ADDMAPPINGFOR(KP_DECIMAL)
        PAX_ADDMAPPINGFOR(KP_HEXADECIMAL)

        PAX_ADDMAPPINGFOR(LCTRL)
        PAX_ADDMAPPINGFOR(LSHIFT)
        PAX_ADDMAPPINGFOR(LALT)
        PAX_ADDMAPPINGFOR(LGUI)
        PAX_ADDMAPPINGFOR(RCTRL)
        PAX_ADDMAPPINGFOR(RSHIFT)
        PAX_ADDMAPPINGFOR(RALT)
        PAX_ADDMAPPINGFOR(RGUI)

        PAX_ADDMAPPINGFOR(MODE)

        PAX_ADDMAPPINGFOR(AUDIONEXT)
        PAX_ADDMAPPINGFOR(AUDIOPREV)
        PAX_ADDMAPPINGFOR(AUDIOSTOP)
        PAX_ADDMAPPINGFOR(AUDIOPLAY)
        PAX_ADDMAPPINGFOR(AUDIOMUTE)
        PAX_ADDMAPPINGFOR(MEDIASELECT)
        PAX_ADDMAPPINGFOR(WWW)
        PAX_ADDMAPPINGFOR(MAIL)
        PAX_ADDMAPPINGFOR(CALCULATOR)
        PAX_ADDMAPPINGFOR(COMPUTER)
        PAX_ADDMAPPINGFOR(AC_SEARCH)
        PAX_ADDMAPPINGFOR(AC_HOME)
        PAX_ADDMAPPINGFOR(AC_BACK)
        PAX_ADDMAPPINGFOR(AC_FORWARD)
        PAX_ADDMAPPINGFOR(AC_STOP)
        PAX_ADDMAPPINGFOR(AC_REFRESH)
        PAX_ADDMAPPINGFOR(AC_BOOKMARKS)

        PAX_ADDMAPPINGFOR(BRIGHTNESSDOWN)
        PAX_ADDMAPPINGFOR(BRIGHTNESSUP)
        PAX_ADDMAPPINGFOR(DISPLAYSWITCH)

        PAX_ADDMAPPINGFOR(KBDILLUMTOGGLE)
        PAX_ADDMAPPINGFOR(KBDILLUMDOWN)
        PAX_ADDMAPPINGFOR(KBDILLUMUP)
        PAX_ADDMAPPINGFOR(EJECT)
        PAX_ADDMAPPINGFOR(SLEEP)

        PAX_ADDMAPPINGFOR(APP1)
        PAX_ADDMAPPINGFOR(APP2)

        PAX_ADDMAPPINGFOR(SDL_NUM_SCANCODES)
    }
}

#undef PAX_ADDMAPPINGFOR